export enum portal{
    NexusPortal,
    ChoosePortal,
    GroupOptions,
    GroupUpsert,
    GroupLookup,
    IndividualOptions,
    IndividualUpsert,
    IndividualLookup,
    LocationOptions,
    LocationUpsert,
    LocationLookup,
    PhoneNumberOptions,
    PhoneNumberUpsert,
    PhoneNumberLookup,
}